### PR TITLE
code cleanup

### PR DESCRIPTION
**Pull request by l3d00m**
update gitignore, remove user specific files, lint cleanup

### CODE REVIEW

**Comment by l3d00m** [comment]
Thanks for the info, I haven't really worked with javadoc yet.

**Comment by l3d00m** [comment]
Is there btw anything simple I can help you with? I have some time to commit :p

**Comment by dotWee** [comment]
I'm currently getting a lot of mails from users with phablet and tablet devices. They are reporting that the dialog covers up the whole screen and not this way:



You could help me investigating that issue.
Are you be able to test this application on tablet emulators running Android 4.2, 4.4 and 5.0?

**Comment by l3d00m** [comment]
Yeah, will try. I just need a moment to download the images for the emulators because I have a very slow connection.

**Pull request merged**
